apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ph-ee-importer-rdbmses.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                image:
                  type: string
                springProfilesActive:
                  type: string
                datasource:
                  type: object
                  properties:
                    username:
                      type: string
                    password:
                      type: string
                    host:
                      type: string
                    port:
                      type: integer
                    schema:
                      type: string
                resources:
                  type: object
                  properties:
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                logging:
                  type: object
                  properties:
                    levelRoot:
                      type: string
                    patternConsole:
                      type: string
                javaToolOptions:
                  type: string
                bucketName:
                  type: string
  scope: Namespaced
  names:
    plural: ph-ee-importer-rdbmses
    singular: ph-ee-importer-rdbms
    kind: PhEeImporterRdbms
    shortNames:
      - peeirdbms

