apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pheeimporterrdbmses.my.custom.group # Use the current naming convention
spec:
  group: my.custom.group
  names:
    kind: PhEeImporterRdbms
    listKind: PhEeImporterRdbmsList
    plural: pheeimporterrdbmses
    singular: pheeimporterrdbms
    shortNames:  # Add short names if required
      - peeirdbms
  scope: Namespaced
  versions:
    - name: v1 
      served: true
      storage: true
      subresources:
        status: {}  # Ensure status is defined as a subresource
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                enabled:
                  type: boolean
                  default: true
                replicas:
                  type: integer
                image:
                  type: string
                springProfilesActive:
                  type: string
                datasource:
                  type: object
                  properties:
                    username:
                      type: string
                    password:
                      type: string
                    host:
                      type: string
                    port:
                      type: integer
                    schema:
                      type: string
                resources:
                  type: object
                  properties:
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                logging:
                  type: object
                  properties:
                    levelRoot:
                      type: string
                    patternConsole:
                      type: string
                javaToolOptions:
                  type: string
                bucketName:
                  type: string
                livenessProbe:
                  type: object
                  properties:
                    path:
                      type: string
                    port:
                      type: integer
                    initialDelaySeconds:
                      type: integer
                    periodSeconds:
                      type: integer
                    failureThreshold:
                      type: integer
                    timeoutSeconds:
                      type: integer
                readinessProbe:
                  type: object
                  properties:
                    path:
                      type: string
                    port:
                      type: integer
                    initialDelaySeconds:
                      type: integer
                    periodSeconds:
                      type: integer
                    failureThreshold:
                      type: integer
                    timeoutSeconds:
                      type: integer
                rbacEnabled:  # Toggle for RBACs
                  type: boolean
                  default: false
                secretEnabled:  # Toggle for Secrets
                  type: boolean
                  default: false
                configMapEnabled:  # Toggle for ConfigMaps
                  type: boolean
                  default: false
                ingressEnabled:  # Toggle for Ingress
                  type: boolean
                  default: false
            status:
              type: object
              properties:
                availableReplicas:
                  type: integer
                errorMessage:
                  type: string
                lastAppliedImage:
                  type: string
                ready:
                  type: boolean
