apiVersion: v1
kind: ServiceAccount
metadata:
  name: ph-ee-operator-sa
  namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ph-ee-operator
  namespace: default
  labels:
    app: ph-ee-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-operator
  template:
    metadata:
      labels:
        app: ph-ee-operator
    spec:
      containers:
        - name: operator
          image: ph-ee-operator:latest # Operator image goes here
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOG_LEVEL
              value: INFO  
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      serviceAccountName: ph-ee-operator-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ph-ee-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - deployments
  - services
  - serviceaccounts
  - configmaps
  - secrets
  - pods
  verbs:
  - '*'
- apiGroups:
  - "apps"
  resources:
  - deployments
  - services
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - "gazelle.mifos.io"
  resources:
  - paymenthubdeployments
  - paymenthubdeployments/status
  verbs:
  - '*' 
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete

  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ph-ee-operator-role-binding
subjects:
  - kind: ServiceAccount
    name: ph-ee-operator-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: ph-ee-operator-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ph-ee-operator-role
  namespace: default
rules:
- apiGroups:
  - gazelle.mifos.io
  resources:
  - paymenthubdeployments
  - paymenthubdeployments/status
  verbs:
  - '*' 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ph-ee-operator-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: ph-ee-operator-sa
    namespace: default
roleRef:
  kind: Role
  name: ph-ee-operator-role
  apiGroup: rbac.authorization.k8s.io
